//
// Created by snownf on 23-12-4.
//

#include "SharedGenerator.h"

namespace jbindgen {

    std::string getAbstractNativeListContent() {
        return "\n"
               "import java.lang.foreign.Arena;\n"
               "import java.lang.foreign.MemorySegment;\n"
               "import java.util.*;\n"
               "import java.util.function.Consumer;\n"
               "import java.util.function.Function;\n"
               "\n"
               "public class AbstractNativeList<T> extends AbstractList<T> implements RandomAccess, Pointer<T> {\n"
               "\n"
               "    protected final MemorySegment ptr;\n"
               "    protected final Function<MemorySegment, T> constructor;\n"
               "    protected final long elementByteSize;\n"
               "\n"
               "    private void ensureValue(MemorySegment ptr, Function<MemorySegment, T> constructor, long sizeof) {\n"
               "        Objects.requireNonNull(ptr);\n"
               "        Objects.requireNonNull(constructor);\n"
               "        if (sizeof <= 0)\n"
               "            throw new IllegalArgumentException(\"Illegal sizeof: \" + sizeof);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(MemorySegment ptr, Function<MemorySegment, T> constructor, long elementByteSize) {\n"
               "        this.ptr = ptr;\n"
               "        this.constructor = constructor;\n"
               "        this.elementByteSize = elementByteSize;\n"
               "        ensureValue(ptr, constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(MemorySegment ptr, long length, Function<MemorySegment, T> constructor, long elementByteSize) {\n"
               "        this(ptr.reinterpret(length * elementByteSize), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(MemorySegment ptr, long length, Arena arena, Consumer<MemorySegment> cleanup, Function<MemorySegment, T> constructor, long elementByteSize) {\n"
               "        this(ptr.reinterpret(length * elementByteSize, arena, cleanup), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(MemorySegment ptr, Arena arena, Consumer<MemorySegment> cleanup, Function<MemorySegment, T> constructor, long elementByteSize) {\n"
               "        this(ptr.reinterpret(arena, cleanup), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(Arena arena, long length, Function<MemorySegment, T> constructor, long elementByteSize) {\n"
               "        this(arena.allocate(elementByteSize * length), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public T get(int index) {\n"
               "        return constructor.apply(ptr.asSlice(index * elementByteSize, elementByteSize));\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public int size() {\n"
               "        return (int) (ptr.byteSize() / elementByteSize);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public void clear() {\n"
               "        ptr.fill((byte) 0);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public AbstractNativeList<T> subList(int fromIndex, int toIndex) {\n"
               "        subListRangeCheck(fromIndex, toIndex, size());\n"
               "        return new AbstractNativeList<>(ptr.asSlice(fromIndex * elementByteSize, (toIndex - fromIndex) * elementByteSize), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public long getElementByteSize() {\n"
               "        return elementByteSize;\n"
               "    }\n"
               "\n"
               "    public Function<MemorySegment, T> getConstructor() {\n"
               "        return constructor;\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public boolean equals(Object o) {\n"
               "        if (o instanceof AbstractNativeList<?> nativeList) return nativeList.ptr.equals(ptr);\n"
               "        return false;\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public int hashCode() {\n"
               "        return ptr.hashCode();\n"
               "    }\n"
               "\n"
               "    public List<T> toList() {\n"
               "        return Collections.unmodifiableList(this);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public MemorySegment pointer() {\n"
               "        return ptr;\n"
               "    }\n"
               "\n"
               "    protected static void subListRangeCheck(int fromIndex, int toIndex, int size) {\n"
               "        if (fromIndex < 0)\n"
               "            throw new IndexOutOfBoundsException(\"fromIndex = \" + fromIndex);\n"
               "        if (toIndex > size)\n"
               "            throw new IndexOutOfBoundsException(\"toIndex = \" + toIndex);\n"
               "        if (fromIndex > toIndex)\n"
               "            throw new IllegalArgumentException(\"fromIndex(\" + fromIndex +\n"
               "                    \") > toIndex(\" + toIndex + \")\");\n"
               "    }\n"
               "}\n";
    }

    std::string getPointerContent() {
        return "\n"
               "import java.lang.foreign.MemorySegment;\n"
               "\n"
               "public interface Pointer<P>{\n"
               "    MemorySegment pointer();\n"
               "}\n";
    }
} // jbindgen