//
// Created by snownf on 23-12-4.
//

#include "SharedGenerator.h"

namespace jbindgen {

    std::string getAbstractNativeListContent() {
        return "\n"
               "import java.lang.foreign.MemorySegment;\n"
               "import java.lang.foreign.SegmentAllocator;\n"
               "import java.util.*;\n"
               "import java.util.function.Consumer;\n"
               "import java.util.function.Function;\n"
               "\n"
               "public class AbstractNativeList<T> extends AbstractList<T> implements RandomAccess, Pointer<T> {\n"
               "\n"
               "    protected final MemorySegment ptr;\n"
               "    protected final Function<Pointer<T>, T> constructor;\n"
               "    protected final long elementByteSize;\n"
               "\n"
               "    private void ensureValue(MemorySegment ptr, Function<Pointer<T>, T> constructor, long byteSize) {\n"
               "        Objects.requireNonNull(ptr);\n"
               "        Objects.requireNonNull(constructor);\n"
               "        if (byteSize <= 0)\n"
               "            throw new IllegalArgumentException(STR.\"Illegal byteSize: \\{byteSize}\");\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(Pointer<T> ptr, Function<Pointer<T>, T> constructor, long elementByteSize) {\n"
               "        this(ptr.pointer(), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    protected AbstractNativeList(MemorySegment ptr, Function<Pointer<T>, T> constructor, long elementByteSize) {\n"
               "        this.ptr = ptr;\n"
               "        this.constructor = constructor;\n"
               "        this.elementByteSize = elementByteSize;\n"
               "        ensureValue(ptr, constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(Pointer<T> ptr, long length, Function<Pointer<T>, T> constructor, long elementByteSize) {\n"
               "        this(ptr.pointer().reinterpret(length * elementByteSize), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList(SegmentAllocator allocator, long length, Function<Pointer<T>, T> constructor, long elementByteSize) {\n"
               "        this(allocator.allocate(elementByteSize * length), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public T get(int index) {\n"
               "        return constructor.apply(pointerAt(index));\n"
               "    }\n"
               "\n"
               "    public Pointer<T> pointerAt(long index) {\n"
               "        return () -> ptr.asSlice(index * elementByteSize, elementByteSize);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public int size() {\n"
               "        return (int) (ptr.byteSize() / elementByteSize);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public void clear() {\n"
               "        ptr.fill((byte) 0);\n"
               "    }\n"
               "\n"
               "    public AbstractNativeList<T> reinterpretSize(long length) {\n"
               "        return new AbstractNativeList<>(ptr.reinterpret(length * elementByteSize), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public AbstractNativeList<T> subList(int fromIndex, int toIndex) {\n"
               "        subListRangeCheck(fromIndex, toIndex, size());\n"
               "        return new AbstractNativeList<>(ptr.asSlice(fromIndex * elementByteSize, (toIndex - fromIndex) * elementByteSize), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public long getElementByteSize() {\n"
               "        return elementByteSize;\n"
               "    }\n"
               "\n"
               "    public Function<Pointer<T>, T> getConstructor() {\n"
               "        return constructor;\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public boolean equals(Object o) {\n"
               "        if (o instanceof AbstractNativeList<?> nativeList) return nativeList.ptr.equals(ptr);\n"
               "        return false;\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public int hashCode() {\n"
               "        return ptr.hashCode();\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public MemorySegment pointer() {\n"
               "        return ptr;\n"
               "    }\n"
               "\n"
               "    protected static void subListRangeCheck(int fromIndex, int toIndex, int size) {\n"
               "        if (fromIndex < 0)\n"
               "            throw new IndexOutOfBoundsException(STR.\"fromIndex = \\{fromIndex}\");\n"
               "        if (toIndex > size)\n"
               "            throw new IndexOutOfBoundsException(STR.\"toIndex = \\{toIndex}\");\n"
               "        if (fromIndex > toIndex)\n"
               "            throw new IllegalArgumentException(STR.\"fromIndex(\\{fromIndex}) > toIndex(\\{toIndex})\");\n"
               "    }\n"
               "}";
    }

    std::string getPointerContent() {
        return "\n"
               "import java.lang.foreign.MemorySegment;\n"
               "\n"
               "public interface Pointer<P>{\n"
               "    MemorySegment pointer();\n"
               "}\n";
    }

    std::string getFunctionUtilsContent() {
        return "\n"
               "import java.lang.foreign.*;\n"
               "import java.lang.invoke.MethodHandle;\n"
               "import java.lang.invoke.MethodHandles;\n"
               "import java.util.Objects;\n"
               "import java.util.Optional;\n"
               "\n"
               "public class FunctionUtils {\n"
               "    public static class InvokeException extends RuntimeException {\n"
               "        public InvokeException(Throwable cause) {\n"
               "            super(cause);\n"
               "        }\n"
               "    }\n"
               "\n"
               "    public static class SymbolNotFound extends RuntimeException {\n"
               "        public SymbolNotFound(String cause) {\n"
               "            super(cause);\n"
               "        }\n"
               "\n"
               "        public SymbolNotFound(Throwable t) {\n"
               "            super(t);\n"
               "        }\n"
               "\n"
               "        public SymbolNotFound() {\n"
               "        }\n"
               "    }\n"
               "\n"
               "    private FunctionUtils() {\n"
               "        throw new UnsupportedOperationException();\n"
               "    }\n"
               "\n"
               "    public static <T> Pointer<T> makePointer(MemorySegment ms) {\n"
               "        return new Pointer<>() {\n"
               "            @Override\n"
               "            public String toString() {\n"
               "                return String.valueOf(ms);\n"
               "            }\n"
               "\n"
               "            @Override\n"
               "            public MemorySegment pointer() {\n"
               "                return ms;\n"
               "            }\n"
               "        };\n"
               "    }\n"
               "\n"
               "    public static MemorySegment toMemorySegment(Arena arena, MethodHandle methodHandle, FunctionDescriptor functionDescriptor) {\n"
               "        return Linker.nativeLinker().upcallStub(methodHandle, functionDescriptor, arena);\n"
               "    }\n"
               "\n"
               "    public static MemorySegment toMemorySegment(MethodHandles.Lookup lookup, Arena arena, FunctionDescriptor functionDescriptor, Object function, String functionName) {\n"
               "        var handle = toMethodHandle(lookup, functionDescriptor, function, functionName);\n"
               "        return toMemorySegment(arena, handle, functionDescriptor);\n"
               "    }\n"
               "\n"
               "    public static MethodHandle toMethodHandle(MethodHandles.Lookup lookup, FunctionDescriptor functionDescriptor, Object function, String functionName) {\n"
               "        try {\n"
               "            return lookup.findVirtual(function.getClass(), functionName, functionDescriptor.toMethodType()).bindTo(function);\n"
               "        } catch (NoSuchMethodException | IllegalAccessException e) {\n"
               "            throw new RuntimeException(e);\n"
               "        }\n"
               "    }\n"
               "\n"
               "    public static Optional<MethodHandle> toMethodHandle(SymbolLookup lookup, String functionName, FunctionDescriptor functionDescriptor, boolean critical) {\n"
               "        return Objects.requireNonNull(lookup).find(Objects.requireNonNull(functionName)).map(ms -> critical ?\n"
               "                Linker.nativeLinker().downcallHandle(ms, functionDescriptor, Linker.Option.critical(true))\n"
               "                : Linker.nativeLinker().downcallHandle(ms, functionDescriptor));\n"
               "    }\n"
               "\n"
               "    public static Optional<MethodHandle> toMethodHandle(MemorySegment memorySegment, FunctionDescriptor functionDescriptor, boolean critical) {\n"
               "        return toMethodHandle(Optional.ofNullable(memorySegment), functionDescriptor, critical);\n"
               "    }\n"
               "\n"
               "    public static Optional<MethodHandle> toMethodHandle(Optional<MemorySegment> memorySegment, FunctionDescriptor functionDescriptor, boolean critical) {\n"
               "        return memorySegment.map(ms -> critical ?\n"
               "                Linker.nativeLinker().downcallHandle(ms, functionDescriptor, Linker.Option.critical(true))\n"
               "                : Linker.nativeLinker().downcallHandle(ms, functionDescriptor));\n"
               "    }\n"
               "}\n";
    }

    std::string getNListContent() {
        return "\n"
               "import java.lang.foreign.MemorySegment;\n"
               "import java.lang.foreign.SegmentAllocator;\n"
               "import java.util.function.Consumer;\n"
               "import java.util.function.Function;\n"
               "\n"
               "public class NList<E extends Pointer<?>> extends AbstractNativeList<E> {\n"
               "    public NList(Pointer<E> ptr, Function<Pointer<E>, E> constructor, long elementByteSize) {\n"
               "        super(ptr, constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public NList(Pointer<E> ptr, long length, Function<Pointer<E>, E> constructor, long elementByteSize) {\n"
               "        super(ptr, length, constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public NList(SegmentAllocator allocator, long length, Function<Pointer<E>, E> constructor, long elementByteSize) {\n"
               "        super(allocator, length, constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public NList<E> reinterpretSize(long length) {\n"
               "        return new NList<>(() -> ptr.reinterpret(length * elementByteSize), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    /**\n"
               "     * @param index   index of the element to replace\n"
               "     * @param element element to be stored at the specified position\n"
               "     * @return the element\n"
               "     */\n"
               "    @Override\n"
               "    public E set(int index, E element) {\n"
               "        if (element.pointer().byteSize() != elementByteSize)\n"
               "            throw new IllegalArgumentException(STR.\"elementByteSize is \\{elementByteSize}, but element.pointer().byteSize() is \\{element.pointer().byteSize()}\");\n"
               "        MemorySegment.copy(element.pointer(), 0, ptr, index * elementByteSize, elementByteSize);\n"
               "        return element;\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public String toString() {\n"
               "        return pointer().byteSize() % elementByteSize == 0 ? super.toString() : STR.\"NList{ptr: \\{ptr}}\";\n"
               "    }\n"
               "}";
    }

    std::string getNPtrListContent() {
        return "\n"
               "import java.lang.foreign.MemorySegment;\n"
               "import java.lang.foreign.SegmentAllocator;\n"
               "import java.lang.foreign.ValueLayout;\n"
               "import java.util.Arrays;\n"
               "import java.util.Collection;\n"
               "import java.util.function.Consumer;\n"
               "import java.util.function.Function;\n"
               "\n"
               "public class NPtrList<T extends Pointer<?>> extends NList<T> {\n"
               "    private final long[] elementsByteSize;\n"
               "\n"
               "    protected NPtrList(MemorySegment ptr, Function<Pointer<T>, T> constructor, long elementByteSize) {\n"
               "        super(() -> ptr, constructor, ValueLayout.ADDRESS.byteSize());\n"
               "        this.elementsByteSize = new long[]{elementByteSize};\n"
               "    }\n"
               "\n"
               "    protected NPtrList(MemorySegment ptr, Function<Pointer<T>, T> constructor, long[] elementsByteSize) {\n"
               "        super(() -> ptr, constructor, ValueLayout.ADDRESS.byteSize());\n"
               "        this.elementsByteSize = elementsByteSize;\n"
               "    }\n"
               "\n"
               "    public NPtrList(Pointer<Pointer<T>> ptr, Function<Pointer<T>, T> constructor, long elementByteSize, long length) {\n"
               "        this(ptr.pointer().reinterpret(length * ValueLayout.ADDRESS.byteSize()), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "    public NPtrList(Pointer<Pointer<T>> ptr, Function<Pointer<T>, T> constructor, long[] elementsByteSize) {\n"
               "        this(ptr.pointer().reinterpret(elementsByteSize.length * ValueLayout.ADDRESS.byteSize()), constructor, elementsByteSize);\n"
               "    }\n"
               "\n"
               "    public NPtrList(SegmentAllocator allocator, Function<Pointer<T>, T> constructor, T[] t) {\n"
               "        this(allocator.allocate(ValueLayout.ADDRESS.byteSize() * t.length), constructor, Arrays.stream(t).mapToLong(v -> v.pointer().byteSize()).toArray());\n"
               "        for (int i = 0; i < t.length; i++) {\n"
               "            ptr.setAtIndex(ValueLayout.ADDRESS, i, t[i].pointer());\n"
               "        }\n"
               "    }\n"
               "\n"
               "    public NPtrList(SegmentAllocator allocator, Function<Pointer<T>, T> constructor, Collection<T> t) {\n"
               "        this(allocator.allocate(ValueLayout.ADDRESS.byteSize() * t.size()), constructor, t.stream().mapToLong(v -> v.pointer().byteSize()).toArray());\n"
               "        int i = 0;\n"
               "        for (T t1 : t) {\n"
               "            ptr.setAtIndex(ValueLayout.ADDRESS, i, t1.pointer());\n"
               "            i++;\n"
               "        }\n"
               "    }\n"
               "\n"
               "    public NPtrList(Pointer<Pointer<T>> ptr, Function<Pointer<T>, T> constructor, long elementByteSize) {\n"
               "        this(ptr.pointer(), constructor, elementByteSize);\n"
               "    }\n"
               "\n"
               "\n"
               "    @Override\n"
               "    public T get(int index) {\n"
               "        return constructor.apply(() -> ptr.getAtIndex(ValueLayout.ADDRESS, index).reinterpret(elementsByteSize.length > 1 ? elementsByteSize[index] : elementsByteSize[0]));\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public T set(int index, T value) {\n"
               "        ptr.setAtIndex(ValueLayout.ADDRESS, index, value.pointer());\n"
               "        return value;\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public void clear() {\n"
               "        throw new UnsupportedOperationException();\n"
               "    }\n"
               "}";
    }

    std::string getValueContent() {
        return "\n"
               "public interface Value<T>{\n"
               "    T value();\n"
               "}\n";
    }

    std::string getSubValueContent(std::string className, std::string basicClassName, std::string specializedList,
                                   std::string specializedListPackageName, std::string sharedValueInterfacePackageName,
                                   std::string sharedPointerPackageName, std::string unused,
                                   std::string basePrimitiveType, std::string baseObjectType) {

        return std::vformat(
                "\n"
                "import {0};\n"
                "import {2};\n"
                "import {8};\n"
                "\n"
                "import java.lang.foreign.MemorySegment;\n"
                "import java.lang.foreign.SegmentAllocator;\n"
                "import java.util.Collection;\n"
                "import java.util.function.Consumer;\n"
                "\n"
                "public class {3}<T> extends {4}<T> {{\n"
                "\n"
                "    public static <T> {5}<{3}<T>> list(Pointer<{3}<T>> ptr) {{\n"
                "        return new {5}<>(ptr, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static <T> {5}<{3}<T>> list(Pointer<{3}<T>> ptr, long length) {{\n"
                "        return new {5}<>(ptr, length, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static <T> {5}<{3}<T>> list(SegmentAllocator allocator, long length) {{\n"
                "        return new {5}<>(allocator, length, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static <T> {5}<{3}<T>> list(SegmentAllocator allocator, {3}<T>[] c) {{\n"
                "        return new {5}<>(allocator, c, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static <T> {5}<{3}<T>> list(SegmentAllocator allocator, Collection<{3}<T>> c) {{\n"
                "        return new {5}<>(allocator, c, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public {3}(Pointer<? extends {3}<T>> ptr) {{\n"
                "        super(ptr);\n"
                "    }}\n"
                "\n"
                "    public {3}({6} value) {{\n"
                "        super(value);\n"
                "    }}\n"
                "\n"
                "    public {3}(Value<{7}> value) {{\n"
                "        super(value);\n"
                "    }}\n"
                "\n"
                "    public {3}({3}<T> value) {{\n"
                "        super(value);\n"
                "    }}\n"
                "}}\n",
                std::make_format_args(sharedPointerPackageName, unused,
                                      sharedValueInterfacePackageName, className,
                                      basicClassName, specializedList,
                                      basePrimitiveType, baseObjectType, specializedListPackageName));
    }

    std::string
    getSubValueContentSpecialized(std::string className, std::string basicClassName, std::string specializedList,
                                  std::string specializedListPackageName, std::string sharedValueInterfacePackageName,
                                  std::string sharedPointerPackageName, std::string sharedVBasicPackageName,
                                  std::string basePrimitiveType, std::string baseObjectType) {

        return std::vformat(
                "\n"
                "import {0};\n"
                "import {2};\n"
                "import {8};\n"
                "import {1};\n"
                "\n"
                "import java.lang.foreign.MemorySegment;\n"
                "import java.lang.foreign.SegmentAllocator;\n"
                "import java.util.Collection;\n"
                "import java.util.function.Consumer;\n"
                "\n"
                "public class {3} extends {4}<{3}> {{\n"
                "\n"
                "    public static {5}<{3}> list(Pointer<{3}> ptr) {{\n"
                "        return new {5}<>(ptr, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static {5}<{3}> list(Pointer<{3}> ptr, long length) {{\n"
                "        return new {5}<>(ptr, length, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static {5}<{3}> list(SegmentAllocator allocator, long length) {{\n"
                "        return new {5}<>(allocator, length, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static {5}<{3}> list(SegmentAllocator allocator, {3}[] c) {{\n"
                "        return new {5}<>(allocator, c, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public static {5}<{3}> list(SegmentAllocator allocator, Collection<{3}> c) {{\n"
                "        return new {5}<>(allocator, c, {3}::new);\n"
                "    }}\n"
                "\n"
                "    public {3}(Pointer<{3}> ptr) {{\n"
                "        super(ptr);\n"
                "    }}\n"
                "\n"
                "    public {3}({6} value) {{\n"
                "        super(value);\n"
                "    }}\n"
                "\n"
                "    public {3}(Value<{7}> value) {{\n"
                "        super(value);\n"
                "    }}\n"
                "\n"
                "    public {3}({3} value) {{\n"
                "        super(value);\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public boolean equals(Object obj) {{\n"
                "        return obj instanceof {3} that && that.value().equals(value());\n"
                "    }}\n"
                "}}\n",
                std::make_format_args(sharedPointerPackageName, sharedVBasicPackageName,
                                      sharedValueInterfacePackageName, className,
                                      basicClassName, specializedList,
                                      basePrimitiveType, baseObjectType, specializedListPackageName));
    }

    std::string getNativeContent(std::string className, std::string baseObjectType, std::string valueLayout,
                                 std::string basePrimitiveType, std::string sharedPointerPackageName,
                                 std::string sharedValuePackageName, std::string theValueTypeName,
                                 std::string theValueTypePkgName) {
        return std::vformat(
                "\n"
                "import {5};\n"
                "import {6};\n"
                "import {7};\n"
                "\n"
                "import java.lang.foreign.MemorySegment;\n"
                "import java.lang.foreign.SegmentAllocator;\n"
                "import java.lang.foreign.ValueLayout;\n"
                "import java.util.function.Consumer;\n"
                "\n"
                "public class {0} implements Pointer<{4}<{1}>>, Value<{1}> {{\n"
                "    public static final long BYTE_SIZE = {2}.byteSize();\n"
                "\n"
                "    private final MemorySegment ptr;\n"
                "\n"
                "    public {0}(Pointer<{4}<?>> ptr) {{\n"
                "        this.ptr = ptr.pointer();\n"
                "    }}\n"
                "\n"
                "    public {0}(SegmentAllocator allocator) {{\n"
                "        ptr = allocator.allocate({2});\n"
                "    }}\n"
                "\n"
                "    public {0}(SegmentAllocator allocator, {3} v) {{\n"
                "        ptr = allocator.allocateFrom({2}, v);\n"
                "    }}\n"
                "\n"
                "    public {0} reinterpretSize() {{\n"
                "        return new {0}(() -> ptr.reinterpret(BYTE_SIZE));\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public {1} value() {{\n"
                "        return get();\n"
                "    }}\n"
                "\n"
                "    public {3} get() {{\n"
                "        return ptr.get({2}, 0);\n"
                "    }}\n"
                "\n"
                "    public {0} set({3} value) {{\n"
                "        ptr.setAtIndex({2}, 0, value);\n"
                "        return this;\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public MemorySegment pointer() {{\n"
                "        return ptr;\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public String toString() {{\n"
                "        return MemorySegment.NULL.address() != ptr.address() && ptr.byteSize() >= BYTE_SIZE\n"
                "                ? String.valueOf(get())\n"
                "                : \"{0}{{ptr: \" + ptr + \"}}\";\n"
                "    }}\n"
                "}}\n", std::make_format_args(className, baseObjectType, valueLayout,
                                              basePrimitiveType, theValueTypeName, sharedPointerPackageName,
                                              sharedValuePackageName, theValueTypePkgName));
    }

    std::string getVListSpecializedContent(std::string className, std::string valueLayout, std::string byteSize,
                                           std::string primitiveObj) {
        return std::vformat(
                "\n"
                "import java.lang.foreign.MemorySegment;\n"
                "import java.lang.foreign.SegmentAllocator;\n"
                "import java.lang.foreign.ValueLayout;\n"
                "import java.util.Collection;\n"
                "import java.util.function.BiConsumer;\n"
                "import java.util.function.Consumer;\n"
                "import java.util.function.Function;\n"
                "\n"
                "public class {0}<T extends Value<{1}>> extends AbstractNativeList<T> {{\n"
                "    public static final long ELEMENT_BYTE_SIZE = {3};\n"
                "\n"
                "    protected {0}(MemorySegment ptr, Function<Pointer<T>, T> constructor) {{\n"
                "        super(ptr, constructor, ELEMENT_BYTE_SIZE);\n"
                "    }}\n"
                "\n"
                "    public {0}(Pointer<T> ptr, Function<Pointer<T>, T> constructor) {{\n"
                "        super(ptr, constructor, ELEMENT_BYTE_SIZE);\n"
                "    }}\n"
                "\n"
                "    public {0}(Pointer<T> ptr, long length, Function<Pointer<T>, T> constructor) {{\n"
                "        super(ptr, length, constructor, ELEMENT_BYTE_SIZE);\n"
                "    }}\n"
                "\n"
                "    public {0}(SegmentAllocator allocator, long length, Function<Pointer<T>, T> constructor, BiConsumer<Long, {0}<T>> creator) {{\n"
                "        super(allocator.allocate(ELEMENT_BYTE_SIZE * length, 4), constructor, ELEMENT_BYTE_SIZE);\n"
                "        for (int i = 0; i < length; i++) {{\n"
                "            creator.accept((long) i, subList(i, i));\n"
                "        }}\n"
                "    }}\n"
                "\n"
                "    public {0}(SegmentAllocator allocator, long length, Function<Pointer<T>, T> constructor) {{\n"
                "        super(allocator.allocate(length * ELEMENT_BYTE_SIZE), constructor, ELEMENT_BYTE_SIZE);\n"
                "    }}\n"
                "\n"
                "    public {0}(SegmentAllocator allocator, T[] objs, Function<Pointer<T>, T> constructor) {{\n"
                "        super(allocator.allocate(objs.length * ELEMENT_BYTE_SIZE), constructor, ELEMENT_BYTE_SIZE);\n"
                "        long index = 0;\n"
                "        for (T obj : objs) {{\n"
                "            ptr.setAtIndex({2}, index, obj.value());\n"
                "            index++;\n"
                "        }}\n"
                "    }}\n"
                "\n"
                "    public {0}(SegmentAllocator allocator, Collection<T> objs, Function<Pointer<T>, T> constructor) {{\n"
                "        super(allocator.allocate(objs.size() * ELEMENT_BYTE_SIZE), constructor, ELEMENT_BYTE_SIZE);\n"
                "        long index = 0;\n"
                "        for (T obj : objs) {{\n"
                "            ptr.setAtIndex({2}, index, obj.value());\n"
                "            index++;\n"
                "        }}\n"
                "    }}\n"
                "\n"
                "    public {0}(SegmentAllocator allocator, {1}[] objs, Function<Pointer<T>, T> constructor) {{\n"
                "        super(allocator.allocate(objs.length * ELEMENT_BYTE_SIZE), constructor, ELEMENT_BYTE_SIZE);\n"
                "        long index = 0;\n"
                "        for ({1} obj : objs) {{\n"
                "            ptr.setAtIndex({2}, index, obj);\n"
                "            index++;\n"
                "        }}\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public T set(int index, T element) {{\n"
                "        ptr.setAtIndex({2}, index, element.value());\n"
                "        return element;\n"
                "    }}\n"
                "\n"
                "    public {1} set(int index, {1} element) {{\n"
                "        ptr.setAtIndex({2}, index, element);\n"
                "        return element;\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public {0}<T> reinterpretSize(long length) {{\n"
                "        return new {0}<>(ptr.reinterpret(length * ELEMENT_BYTE_SIZE), constructor);\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public {0}<T> subList(int fromIndex, int toIndex) {{\n"
                "        subListRangeCheck(fromIndex, toIndex, size());\n"
                "        return new {0}<>(ptr.asSlice(fromIndex * elementByteSize, (toIndex - fromIndex) * elementByteSize), constructor);\n"
                "    }}\n"
                "\n"
                "    @Override\n"
                "    public String toString() {{\n"
                "        return pointer().byteSize() % elementByteSize == 0 ? super.toString() : STR.\"{0}{{ptr:\\{{ptr}}}}\";\n"
                "    }}\n"
                "}}\n", std::make_format_args(className, primitiveObj, valueLayout, byteSize));
    }

    std::string
    getBasicValueContent(std::string sharedValueInterfacePackageName, std::string sharedPointerPackageName,
                         std::string className,
                         std::string primitiveType, std::string primitiveObjType, std::string valueLayout) {
        return std::vformat("\n"
                            "import {0};\n"
                            "import {1};\n"
                            "\n"
                            "import java.lang.foreign.MemoryLayout;\n"
                            "import java.lang.foreign.MemorySegment;\n"
                            "import java.lang.foreign.ValueLayout;\n"
                            "\n"
                            "public class {2}<T> implements Value<{4}> {{\n"
                            "    public static final MemoryLayout MEMORY_LAYOUT = {5};\n"
                            "    public static final long BYTE_SIZE = MEMORY_LAYOUT.byteSize();\n"
                            "    private final {3} value;\n"
                            "\n"
                            "    public {2}(Pointer<? extends {2}<T>> ptr) {{\n"
                            "        this.value = ptr.pointer().get({5}, 0);\n"
                            "    }}\n"
                            "\n"
                            "    public {2}({4} value) {{\n"
                            "        this.value = value;\n"
                            "    }}\n"
                            "\n"
                            "    public {2}(Value<{4}> value) {{\n"
                            "        this.value = value.value();\n"
                            "    }}\n"
                            "\n"
                            "    @Override\n"
                            "    public {4} value() {{\n"
                            "        return value;\n"
                            "    }}\n"
                            "\n"
                            "    @Override\n"
                            "    public boolean equals(Object obj) {{\n"
                            "        return obj instanceof {2}<?> that && that.value().equals(value);\n"
                            "    }}\n"
                            "\n"
                            "    @Override\n"
                            "    public int hashCode() {{\n"
                            "        return value().hashCode();\n"
                            "    }}\n"
                            "\n"
                            "    @Override\n"
                            "    public String toString() {{\n"
                            "        return String.valueOf(value);\n"
                            "    }}\n"
                            "}}",
                            std::make_format_args(sharedValueInterfacePackageName, sharedPointerPackageName, className,
                                                  primitiveType, primitiveObjType, valueLayout));
    }

    std::string getNStringContent(const std::string &vi8ValuePackageName) {
        return "\n"
               "import " + vi8ValuePackageName + ";\n" +
               "\n"
               "import java.lang.foreign.MemorySegment;\n"
               "import java.lang.foreign.SegmentAllocator;\n"
               "import java.lang.foreign.ValueLayout;\n"
               "import java.nio.charset.StandardCharsets;\n"
               "import java.util.Collection;\n"
               "import java.util.function.Consumer;\n"
               "\n"
               "public class NString extends VI8List<VI8<Byte>> implements Value<String> {\n"
               "    public static class NativeStringList extends NList<NString> {\n"
               "        private static final long ELEMENT_BYTE_SIZE = ValueLayout.JAVA_LONG.byteSize();\n"
               "\n"
               "        public NativeStringList(Pointer<Pointer<VI8<Byte>>> ptr) {\n"
               "            super(ptr::pointer, nStringPointer -> new NString(nStringPointer::pointer), ELEMENT_BYTE_SIZE);\n"
               "        }\n"
               "\n"
               "        protected NativeStringList(MemorySegment ptr) {\n"
               "            this(() -> ptr);\n"
               "        }\n"
               "\n"
               "        public NativeStringList(Pointer<Pointer<VI8<Byte>>> ptr, long length) {\n"
               "            this(ptr.pointer().reinterpret(length * ELEMENT_BYTE_SIZE));\n"
               "        }\n"
               "\n"
               "        public NativeStringList(SegmentAllocator allocator, String[] strings) {\n"
               "            this(allocator.allocate(ValueLayout.ADDRESS, strings.length));\n"
               "            int i = 0;\n"
               "            for (String string : strings) {\n"
               "                ptr.setAtIndex(ValueLayout.ADDRESS, i, allocator.allocateFrom(string));\n"
               "                i++;\n"
               "            }\n"
               "        }\n"
               "\n"
               "        public NativeStringList(SegmentAllocator allocator, Collection<String> strings) {\n"
               "            this(allocator.allocate(ValueLayout.ADDRESS, strings.size()));\n"
               "            int i = 0;\n"
               "            for (String string : strings) {\n"
               "                ptr.setAtIndex(ValueLayout.ADDRESS, i, allocator.allocateFrom(string));\n"
               "                i++;\n"
               "            }\n"
               "        }\n"
               "\n"
               "        @Override\n"
               "        public NativeStringList subList(int fromIndex, int toIndex) {\n"
               "            subListRangeCheck(fromIndex, toIndex, size());\n"
               "            return new NativeStringList(super.pointer().asSlice(fromIndex * ELEMENT_BYTE_SIZE, (toIndex - fromIndex) * ELEMENT_BYTE_SIZE));\n"
               "        }\n"
               "\n"
               "        @Override\n"
               "        public void clear() {\n"
               "            throw new UnsupportedOperationException();\n"
               "        }\n"
               "\n"
               "        @Override\n"
               "        public NString get(int index) {\n"
               "            MemorySegment segment = super.pointer().getAtIndex(ValueLayout.ADDRESS, index).reinterpret(Integer.MAX_VALUE);\n"
               "            return constructor.apply(() -> segment);\n"
               "        }\n"
               "\n"
               "        @Override\n"
               "        public NString set(int index, NString element) {\n"
               "            ptr.setAtIndex(ValueLayout.ADDRESS, index, element.pointer());\n"
               "            return element;\n"
               "        }\n"
               "    }\n"
               "\n"
               "    public static NList<NString> list(Pointer<Pointer<VI8<Byte>>> ptr, long length) {\n"
               "        return new NativeStringList(ptr, length);\n"
               "    }\n"
               "\n"
               "    public static NList<NString> list(SegmentAllocator allocator, String[] strings) {\n"
               "        MemorySegment strPtr = allocator.allocate(ValueLayout.ADDRESS, strings.length);\n"
               "        int i = 0;\n"
               "        for (String string : strings) {\n"
               "            strPtr.setAtIndex(ValueLayout.ADDRESS, i, allocator.allocateFrom(string));\n"
               "            i++;\n"
               "        }\n"
               "        return new NativeStringList(strPtr);\n"
               "    }\n"
               "\n"
               "    public static NList<NString> list(SegmentAllocator allocator, Collection<String> strings) {\n"
               "        MemorySegment strPtr = allocator.allocate(ValueLayout.ADDRESS, strings.size());\n"
               "        int i = 0;\n"
               "        for (String string : strings) {\n"
               "            strPtr.setAtIndex(ValueLayout.ADDRESS, i, allocator.allocateFrom(string));\n"
               "            i++;\n"
               "        }\n"
               "        return new NativeStringList(strPtr);\n"
               "    }\n"
               "\n"
               "    public NString(Pointer<VI8<Byte>> ptr) {\n"
               "        super(ptr, VI8::new);\n"
               "    }\n"
               "\n"
               "    protected NString(MemorySegment ptr) {\n"
               "        super(ptr, VI8::new);\n"
               "    }\n"
               "\n"
               "    public NString(Pointer<VI8<Byte>> ptr, long byteSize) {\n"
               "        this(ptr.pointer().reinterpret(byteSize));\n"
               "    }\n"
               "\n"
               "    public NString(SegmentAllocator allocator, String s) {\n"
               "        this(allocator.allocateFrom(s, StandardCharsets.UTF_8));\n"
               "    }\n"
               "\n"
               "    public NString reinterpretSize(long byteSize) {\n"
               "        return new NString(() -> ptr.reinterpret(byteSize));\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public String value() {\n"
               "        return get();\n"
               "    }\n"
               "\n"
               "    public String get() {\n"
               "        return MemorySegment.NULL.address() == ptr.address() ? null : toString();\n"
               "    }\n"
               "\n"
               "    public NString set(String value) {\n"
               "        ptr.setString(0, value, StandardCharsets.UTF_8);\n"
               "        return this;\n"
               "    }\n"
               "\n"
               "    @Override\n"
               "    public String toString() {\n"
               "        return MemorySegment.NULL.address() == ptr.address()\n"
               "                ? STR.\"NString{ptr=\\{ptr}\\{'}'}\"\n"
               "                : ptr.getString(0, StandardCharsets.UTF_8);\n"
               "    }\n"
               "}";
    }
} // jbindgen